### ISSUE TITLE
Error: pod info for cpu count

### ISSUE THREAD

**Issue by panbanda** [balena-io/open-balena#117]
I am on a DO Ubuntu 20 running the latest commands from https://www.balena.io/open/docs/getting-started/ and when I run `./scripts/compose up -d` I get these for the vpn container.

```sh
May 29 20:02:53 ea35d670a755 systemd[1]: Started balena-root-ca.
May 29 20:02:53 ea35d670a755 systemd[1]: Starting open-balena-vpn...
May 29 20:02:53 ea35d670a755 systemd[1]: Started open-balena-vpn.
May 29 20:02:53 ea35d670a755 systemd[1]: Startup finished in 6.765s.
May 29 20:02:55 ea35d670a755 vpn[998]: Could not find pod info for cpu count: Error: ENOENT: no such file or directory, open '/etc/podinfo/cpu_request'
May 29 20:02:55 ea35d670a755 vpn[998]:     at Object.openSync (fs.js:476:3)
May 29 20:02:55 ea35d670a755 vpn[998]:     at Object.readFileSync (fs.js:377:35)
May 29 20:02:55 ea35d670a755 vpn[998]:     at Object.exports.getInstanceCount (/usr/src/app/src/utils/config.ts:69:7)
May 29 20:02:55 ea35d670a755 vpn[998]:     at Object.<anonymous> (/usr/src/app/src/app.ts:55:28)
May 29 20:02:55 ea35d670a755 vpn[998]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
May 29 20:02:55 ea35d670a755 vpn[998]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
May 29 20:02:55 ea35d670a755 vpn[998]:     at Module.load (internal/modules/cjs/loader.js:928:32)
May 29 20:02:55 ea35d670a755 vpn[998]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
May 29 20:02:55 ea35d670a755 vpn[998]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
May 29 20:02:55 ea35d670a755 vpn[998]:     at internal/main/run_main_module.js:17:47 {
May 29 20:02:55 ea35d670a755 vpn[998]:   errno: -2,
May 29 20:02:55 ea35d670a755 vpn[998]:   syscall: 'open',
May 29 20:02:55 ea35d670a755 vpn[998]:   code: 'ENOENT',
May 29 20:02:55 ea35d670a755 vpn[998]:   path: '/etc/podinfo/cpu_request'
May 29 20:02:55 ea35d670a755 vpn[998]: }
May 29 20:02:55 ea35d670a755 vpn[998]: Defaulting to all cores: 1
May 29 20:02:55 ea35d670a755 vpn[998]: notice: [master] open-balena-vpn@9.17.4 process started with pid=998
May 29 20:02:55 ea35d670a755 vpn[998]: debug: [master] registering as service instance...
May 29 20:02:57 ea35d670a755 kernel: br-a4e073c4cfd2: port 8(vethae7104e) entered disabled state
May 29 20:02:57 ea35d670a755 kernel: veth04a6c4c: renamed from eth0
May 29 20:02:57 ea35d670a755 kernel: br-a4e073c4cfd2: port 8(vethae7104e) entered disabled state
May 29 20:02:57 ea35d670a755 kernel: device vethae7104e left promiscuous mode
May 29 20:02:57 ea35d670a755 kernel: br-a4e073c4cfd2: port 8(vethae7104e) entered disabled state
May 29 20:02:57 ea35d670a755 kernel: br-a4e073c4cfd2: port 8(veth67eaea2) entered blocking state
May 29 20:02:57 ea35d670a755 kernel: br-a4e073c4cfd2: port 8(veth67eaea2) entered disabled state
May 29 20:02:57 ea35d670a755 kernel: device veth67eaea2 entered promiscuous mode
May 29 20:02:57 ea35d670a755 kernel: br-a4e073c4cfd2: port 8(veth67eaea2) entered blocking state
May 29 20:02:57 ea35d670a755 kernel: br-a4e073c4cfd2: port 8(veth67eaea2) entered forwarding state
May 29 20:02:58 ea35d670a755 kernel: br-a4e073c4cfd2: port 8(veth67eaea2) entered disabled state
May 29 20:02:58 ea35d670a755 kernel: eth0: renamed from veth97c21e5
May 29 20:02:58 ea35d670a755 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth67eaea2: link becomes ready
May 29 20:02:58 ea35d670a755 kernel: br-a4e073c4cfd2: port 8(veth67eaea2) entered blocking state
May 29 20:02:58 ea35d670a755 kernel: br-a4e073c4cfd2: port 8(veth67eaea2) entered forwarding state
```

**Comment by ab77** [comment]
This component supports running in Kubernetes, this message can be safely ignore running outside of that environment.
