### ISSUE TITLE
SyntaxError: Could not resolve relationship mapping from 'device type' to 'is default for,application'

### ISSUE THREAD

**Issue by pdcastro** [balena-io/open-balena#121]
The balena SDK for Node.js deprecated the [models.config.getDeviceTypes](https://www.balena.io/docs/reference/sdk/node-sdk/#balena.models.config.getDeviceTypes) method, and the `balena devices supported` command of balena CLI v12.44.20 and later started using a new balena SDK method:

* new: `getBalenaSdk().models.deviceType.getAllSupported()`  
https://www.balena.io/docs/reference/sdk/node-sdk/#balena.models.deviceType.getAllSupported
* old: `getBalenaSdk().models.config.getDeviceTypes()`  
https://www.balena.io/docs/reference/sdk/node-sdk/#balena.models.config.getDeviceTypes

Running `balena devices supported` with balena CLI version 12.44.20 works with balenaCloud, but causes an internal server error with openBalena (tested with openBalena v3.3.2). The `journalctl` logs for the `openbalena_api_1` show:
```
$ docker exec -it openbalena_api_1 journalctl -fab
...
Jun 21 16:09:26 0b6ea070a88e api[986]: Parsing GET /resin/device_type?$orderby=name%20asc&$filter=is_default_for__application/any(idfa:(idfa/is_host%20eq%20true)%20and%20(idfa/is_archived%20eq%20false))&$expand=is_of__cpu_architecture($select=slug)&$select=slug,name
Jun 21 16:09:26 0b6ea070a88e api[986]: Failed to translate url:  {
Jun 21 16:09:26 0b6ea070a88e api[986]: 	"resource": "device_type",
Jun 21 16:09:26 0b6ea070a88e api[986]: 	"options": {
Jun 21 16:09:26 0b6ea070a88e api[986]: 		"$select": {
Jun 21 16:09:26 0b6ea070a88e api[986]: 			"properties": [
Jun 21 16:09:26 0b6ea070a88e api[986]: 				{
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"name": "slug",
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"property": null,
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"count": null
Jun 21 16:09:26 0b6ea070a88e api[986]: 				},
Jun 21 16:09:26 0b6ea070a88e api[986]: 				{
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"name": "name",
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"property": null,
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"count": null
Jun 21 16:09:26 0b6ea070a88e api[986]: 				}
Jun 21 16:09:26 0b6ea070a88e api[986]: 			]
Jun 21 16:09:26 0b6ea070a88e api[986]: 		},
Jun 21 16:09:26 0b6ea070a88e api[986]: 		"$filter": {
Jun 21 16:09:26 0b6ea070a88e api[986]: 			"name": "is_default_for__application",
Jun 21 16:09:26 0b6ea070a88e api[986]: 			"lambda": {
Jun 21 16:09:26 0b6ea070a88e api[986]: 				"expression": [
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"and",
Jun 21 16:09:26 0b6ea070a88e api[986]: 					[
Jun 21 16:09:26 0b6ea070a88e api[986]: 						"eq",
Jun 21 16:09:26 0b6ea070a88e api[986]: 						{
Jun 21 16:09:26 0b6ea070a88e api[986]: 							"name": "idfa",
Jun 21 16:09:26 0b6ea070a88e api[986]: 							"property": {
Jun 21 16:09:26 0b6ea070a88e api[986]: 								"name": "is_host",
Jun 21 16:09:26 0b6ea070a88e api[986]: 								"property": null,
Jun 21 16:09:26 0b6ea070a88e api[986]: 								"count": null
Jun 21 16:09:26 0b6ea070a88e api[986]: 							},
Jun 21 16:09:26 0b6ea070a88e api[986]: 							"count": null
Jun 21 16:09:26 0b6ea070a88e api[986]: 						},
Jun 21 16:09:26 0b6ea070a88e api[986]: 						{
Jun 21 16:09:26 0b6ea070a88e api[986]: 							"bind": 0
Jun 21 16:09:26 0b6ea070a88e api[986]: 						}
Jun 21 16:09:26 0b6ea070a88e api[986]: 					],
Jun 21 16:09:26 0b6ea070a88e api[986]: 					[
Jun 21 16:09:26 0b6ea070a88e api[986]: 						"eq",
Jun 21 16:09:26 0b6ea070a88e api[986]: 						{
Jun 21 16:09:26 0b6ea070a88e api[986]: 							"name": "idfa",
Jun 21 16:09:26 0b6ea070a88e api[986]: 							"property": {
Jun 21 16:09:26 0b6ea070a88e api[986]: 								"name": "is_archived",
Jun 21 16:09:26 0b6ea070a88e api[986]: 								"property": null,
Jun 21 16:09:26 0b6ea070a88e api[986]: 								"count": null
Jun 21 16:09:26 0b6ea070a88e api[986]: 							},
Jun 21 16:09:26 0b6ea070a88e api[986]: 							"count": null
Jun 21 16:09:26 0b6ea070a88e api[986]: 						},
Jun 21 16:09:26 0b6ea070a88e api[986]: 						{
Jun 21 16:09:26 0b6ea070a88e api[986]: 							"bind": 1
Jun 21 16:09:26 0b6ea070a88e api[986]: 						}
Jun 21 16:09:26 0b6ea070a88e api[986]: 					]
Jun 21 16:09:26 0b6ea070a88e api[986]: 				],
Jun 21 16:09:26 0b6ea070a88e api[986]: 				"identifier": "idfa",
Jun 21 16:09:26 0b6ea070a88e api[986]: 				"method": "any"
Jun 21 16:09:26 0b6ea070a88e api[986]: 			}
Jun 21 16:09:26 0b6ea070a88e api[986]: 		},
Jun 21 16:09:26 0b6ea070a88e api[986]: 		"$expand": {
Jun 21 16:09:26 0b6ea070a88e api[986]: 			"properties": [
Jun 21 16:09:26 0b6ea070a88e api[986]: 				{
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"name": "is_of__cpu_architecture",
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"property": null,
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"count": null,
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"options": {
Jun 21 16:09:26 0b6ea070a88e api[986]: 						"$select": {
Jun 21 16:09:26 0b6ea070a88e api[986]: 							"properties": [
Jun 21 16:09:26 0b6ea070a88e api[986]: 								{
Jun 21 16:09:26 0b6ea070a88e api[986]: 									"name": "slug",
Jun 21 16:09:26 0b6ea070a88e api[986]: 									"property": null,
Jun 21 16:09:26 0b6ea070a88e api[986]: 									"count": null
Jun 21 16:09:26 0b6ea070a88e api[986]: 								}
Jun 21 16:09:26 0b6ea070a88e api[986]: 							]
Jun 21 16:09:26 0b6ea070a88e api[986]: 						}
Jun 21 16:09:26 0b6ea070a88e api[986]: 					}
Jun 21 16:09:26 0b6ea070a88e api[986]: 				}
Jun 21 16:09:26 0b6ea070a88e api[986]: 			]
Jun 21 16:09:26 0b6ea070a88e api[986]: 		},
Jun 21 16:09:26 0b6ea070a88e api[986]: 		"$orderby": {
Jun 21 16:09:26 0b6ea070a88e api[986]: 			"properties": [
Jun 21 16:09:26 0b6ea070a88e api[986]: 				{
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"name": "name",
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"property": null,
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"count": null,
Jun 21 16:09:26 0b6ea070a88e api[986]: 					"order": "asc"
Jun 21 16:09:26 0b6ea070a88e api[986]: 				}
Jun 21 16:09:26 0b6ea070a88e api[986]: 			]
Jun 21 16:09:26 0b6ea070a88e api[986]: 		}
Jun 21 16:09:26 0b6ea070a88e api[986]: 	}
Jun 21 16:09:26 0b6ea070a88e api[986]: } GET SyntaxError: Could not resolve relationship mapping from 'device type' to 'is default for,application'
Jun 21 16:09:26 0b6ea070a88e api[986]:     at OData2AbstractSQL.ResolveRelationship (/usr/src/app/node_modules/@balena/odata-to-abstract-sql/src/odata-to-abstract-sql.ts:817:10)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at OData2AbstractSQL.NavigateResources (/usr/src/app/node_modules/@balena/odata-to-abstract-sql/src/odata-to-abstract-sql.ts:1358:36)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at OData2AbstractSQL.AddNavigation (/usr/src/app/node_modules/@balena/odata-to-abstract-sql/src/odata-to-abstract-sql.ts:1415:27)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at OData2AbstractSQL.Lambda (/usr/src/app/node_modules/@balena/odata-to-abstract-sql/src/odata-to-abstract-sql.ts:1050:26)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at OData2AbstractSQL.Property (/usr/src/app/node_modules/@balena/odata-to-abstract-sql/src/odata-to-abstract-sql.ts:1146:16)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at OData2AbstractSQL.ReferencedProperty (/usr/src/app/node_modules/@balena/odata-to-abstract-sql/src/odata-to-abstract-sql.ts:1083:21)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at OData2AbstractSQL.BooleanMatch (/usr/src/app/node_modules/@balena/odata-to-abstract-sql/src/odata-to-abstract-sql.ts:982:19)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at OData2AbstractSQL.SelectFilter (/usr/src/app/node_modules/@balena/odata-to-abstract-sql/src/odata-to-abstract-sql.ts:694:22)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at OData2AbstractSQL.AddQueryOptions (/usr/src/app/node_modules/@balena/odata-to-abstract-sql/src/odata-to-abstract-sql.ts:1337:9)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at OData2AbstractSQL.PathSegment (/usr/src/app/node_modules/@balena/odata-to-abstract-sql/src/odata-to-abstract-sql.ts:595:9)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at OData2AbstractSQL.match (/usr/src/app/node_modules/@balena/odata-to-abstract-sql/src/odata-to-abstract-sql.ts:337:24)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at /usr/src/app/node_modules/@balena/pinejs/src/sbvr-api/uri-parser.ts:165:43
Jun 21 16:09:26 0b6ea070a88e api[986]:     at /usr/src/app/node_modules/es5-ext/function/#/partial.js:12:16
Jun 21 16:09:26 0b6ea070a88e api[986]:     at /usr/src/app/node_modules/memoizee/lib/configure-map.js:61:24
Jun 21 16:09:26 0b6ea070a88e api[986]:     at /usr/src/app/node_modules/memoizee/lib/weak.js:87:21
Jun 21 16:09:26 0b6ea070a88e api[986]:     at /usr/src/app/node_modules/@balena/pinejs/src/sbvr-api/uri-parser.ts:242:50
Jun 21 16:09:26 0b6ea070a88e api[986]:     at Object.translateUri (/usr/src/app/node_modules/@balena/pinejs/src/sbvr-api/uri-parser.ts:404:28)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at prepareRequest (/usr/src/app/node_modules/@balena/pinejs/src/sbvr-api/sbvr-utils.ts:1014:48)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at /usr/src/app/node_modules/@balena/pinejs/src/sbvr-api/sbvr-utils.ts:1030:16
Jun 21 16:09:26 0b6ea070a88e api[986]:     at mapTill (/usr/src/app/node_modules/@balena/pinejs/src/sbvr-api/control-flow.ts:45:19)
Jun 21 16:09:26 0b6ea070a88e api[986]:     at /usr/src/app/node_modules/@balena/pinejs/src/sbvr-api/sbvr-utils.ts:1024:20
Jun 21 16:09:26 0b6ea070a88e api[986]:     at handleODataRequest (/usr/src/app/node_modules/@balena/pinejs/src/sbvr-api/sbvr-utils.ts:1089:21)
Jun 21 16:09:26 0b6ea070a88e api[986]: 2021-06-21T16:09:26.579Z 192.168.1.122 a/2 GET /resin/device_type?$orderby=name asc&$filter=is_default_for__application/any(idfa:(idfa/is_host eq true) and (idfa/is_archived eq false))&$expand=is_of__cpu_architecture($select=slug)&$select=slug,name 500 10.931ms balena-sdk/15.36.0
Jun 21 16:09:26 0b6ea070a88e api[986]: 2021-06-21T16:09:26.584Z 192.168.1.122 a/2 GET /device-types/v1 200 17.592ms balena-sdk/15.36.0
```

**Comment by thgreasi** [comment]
Resolved by #123 in v3.4.0
