### ISSUE TITLE
"balena os configure" induces hundreds of AccessDenied errors in api container and crashes

### ISSUE THREAD

**Issue by justinasjaronis** [balena-io/open-balena#165]
If device is to be configured first time,  client side "balena os configure" command induces a hundreds if not thousands of such errors in API container:

Mar 15 19:26:05 1b8ea8a621f5 api[1214]: Failed to get device type build data for ccon-01/2.102.0 Access Denied AccessDenied: Access Denied
Mar 15 19:26:05 1b8ea8a621f5 api[1214]:     at Request.extractError (/usr/src/app/node_modules/aws-sdk/lib/services/s3.js:711:35)
Mar 15 19:26:05 1b8ea8a621f5 api[1214]:     at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
Mar 15 19:26:05 1b8ea8a621f5 api[1214]:     at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
Mar 15 19:26:05 1b8ea8a621f5 api[1214]:     at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/request.js:686:14)
Mar 15 19:26:05 1b8ea8a621f5 api[1214]:     at Request.transition (/usr/src/app/node_modules/aws-sdk/lib/request.js:22:10)
Mar 15 19:26:05 1b8ea8a621f5 api[1214]:     at AcceptorStateMachine.runTo (/usr/src/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
Mar 15 19:26:05 1b8ea8a621f5 api[1214]:     at /usr/src/app/node_modules/aws-sdk/lib/state_machine.js:26:10

and 4 from 5 times "balena os configure" ends with "ECONNRESET" error. But, sometimes (1 from 5 times) this command succeeds.

I'm using versions from master branch:
 OPENBALENA_API_VERSION_TAG=v0.209.2
 OPENBALENA_DB_VERSION_TAG=v5.1.2
 OPENBALENA_MDNS_PUBLISHER_VERSION_TAG=v1.9.2
 OPENBALENA_REGISTRY_VERSION_TAG=v2.25.3
 OPENBALENA_S3_VERSION_TAG=v2.13.10
 OPENBALENA_VPN_VERSION_TAG=v11.4.6

**Comment by dfunckt** [comment]
Can you try deleting all resources related to the `ccon-01` device-type (and application, if it exists)? You'll need direct database access to do so.

**Comment by justinasjaronis** [comment]
Unfortunately I don't see anythin with such device types or aliases .

Strange types are: srd3-xavier, ccon-01, pc-20, lv-dart, nitrogen8mm-dwe,  srd3-xavier .

Acttually I grepped both database dump, openbalena runtime folder and balena-cli source (from which I build cli I use) and I didn't manage to find anything. What can it be?

May 06 16:00:59 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.101.3 Access Denied AccessDenied: Access Denied
May 06 16:00:59 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.100.8 Access Denied AccessDenied: Access Denied
May 06 16:00:59 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.20 Access Denied AccessDenied: Access Denied
May 06 16:00:59 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.103.4 Access Denied AccessDenied: Access Denied
May 06 16:00:59 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.99.25+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:00 1b8ea8a621f5 api[1211]: Failed to get device type build data for imx8mmebcrs08a2/2.100.2 Access Denied AccessDenied: Access Denied
May 06 16:01:00 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.101.2 Access Denied AccessDenied: Access Denied
May 06 16:01:00 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.18 Access Denied AccessDenied: Access Denied
May 06 16:01:00 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.100.6 Access Denied AccessDenied: Access Denied
May 06 16:01:00 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.103.3 Access Denied AccessDenied: Access Denied
May 06 16:01:00 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.99.22 Access Denied AccessDenied: Access Denied
May 06 16:01:00 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.101.1+rev2 Access Denied AccessDenied: Access Denied
May 06 16:01:00 1b8ea8a621f5 api[1211]: Failed to get device type build data for imx8mmebcrs08a2/2.100.0+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:00 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.17 Access Denied AccessDenied: Access Denied
May 06 16:01:00 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.100.5 Access Denied AccessDenied: Access Denied
May 06 16:01:01 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.103.2 Access Denied AccessDenied: Access Denied
May 06 16:01:01 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.99.21 Access Denied AccessDenied: Access Denied
May 06 16:01:01 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.101.1+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:01 1b8ea8a621f5 api[1211]: Failed to get device type build data for imx8mmebcrs08a2/2.100.0 Access Denied AccessDenied: Access Denied
May 06 16:01:01 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.16 Access Denied AccessDenied: Access Denied
May 06 16:01:01 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.100.4 Access Denied AccessDenied: Access Denied
May 06 16:01:01 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.103.1+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:02 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.99.19 Access Denied AccessDenied: Access Denied
May 06 16:01:02 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.101.1 Access Denied AccessDenied: Access Denied
May 06 16:01:02 1b8ea8a621f5 api[1211]: Failed to get device type build data for imx8mmebcrs08a2/2.98.11+rev6 Access Denied AccessDenied: Access Denied
May 06 16:01:02 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.14+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:02 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.100.3 Access Denied AccessDenied: Access Denied
May 06 16:01:02 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.103.1 Access Denied AccessDenied: Access Denied
May 06 16:01:02 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.99.18 Access Denied AccessDenied: Access Denied
May 06 16:01:03 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.101.0+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:03 1b8ea8a621f5 api[1211]: Failed to get device type build data for imx8mmebcrs08a2/2.98.11+rev5 Access Denied AccessDenied: Access Denied
May 06 16:01:03 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.100.2 Access Denied AccessDenied: Access Denied
May 06 16:01:03 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.14 Access Denied AccessDenied: Access Denied
May 06 16:01:03 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.103.0 Access Denied AccessDenied: Access Denied
May 06 16:01:03 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.99.4+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:03 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.101.0 Access Denied AccessDenied: Access Denied
May 06 16:01:04 1b8ea8a621f5 api[1211]: Failed to get device type build data for imx8mmebcrs08a2/2.98.11+rev4 Access Denied AccessDenied: Access Denied
May 06 16:01:04 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.13 Access Denied AccessDenied: Access Denied
May 06 16:01:04 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.100.1 Access Denied AccessDenied: Access Denied
May 06 16:01:04 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.102.6 Access Denied AccessDenied: Access Denied
May 06 16:01:04 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.99.4 Access Denied AccessDenied: Access Denied
May 06 16:01:04 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.26+rev4 Access Denied AccessDenied: Access Denied
May 06 16:01:04 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.12 Access Denied AccessDenied: Access Denied
May 06 16:01:04 1b8ea8a621f5 api[1211]: Failed to get device type build data for imx8mmebcrs08a2/2.98.11+rev3 Access Denied AccessDenied: Access Denied
May 06 16:01:04 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.100.0 Access Denied AccessDenied: Access Denied
May 06 16:01:05 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.102.5 Access Denied AccessDenied: Access Denied
May 06 16:01:05 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.99.3 Access Denied AccessDenied: Access Denied
May 06 16:01:05 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.26+rev3 Access Denied AccessDenied: Access Denied
May 06 16:01:05 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.11 Access Denied AccessDenied: Access Denied
May 06 16:01:05 1b8ea8a621f5 api[1211]: Failed to get device type build data for imx8mmebcrs08a2/2.98.11+rev2 Access Denied AccessDenied: Access Denied
May 06 16:01:05 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.98.42+rev3 Access Denied AccessDenied: Access Denied
May 06 16:01:05 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.102.4+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:06 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.99.2 Access Denied AccessDenied: Access Denied
May 06 16:01:06 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.26+rev2 Access Denied AccessDenied: Access Denied
May 06 16:01:06 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.10 Access Denied AccessDenied: Access Denied
May 06 16:01:06 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.98.42+rev2 Access Denied AccessDenied: Access Denied
May 06 16:01:06 1b8ea8a621f5 api[1211]: Failed to get device type build data for imx8mmebcrs08a2/2.98.11 Access Denied AccessDenied: Access Denied
May 06 16:01:06 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.102.4 Access Denied AccessDenied: Access Denied
May 06 16:01:06 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.99.0+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:07 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.26+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:07 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.9 Access Denied AccessDenied: Access Denied
May 06 16:01:07 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.98.42+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:07 1b8ea8a621f5 api[1211]: Failed to get device type build data for imx8mmebcrs08a2/2.91.5 Access Denied AccessDenied: Access Denied
May 06 16:01:07 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.102.3 Access Denied AccessDenied: Access Denied
May 06 16:01:07 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.99.0 Access Denied AccessDenied: Access Denied
May 06 16:01:07 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.26 Access Denied AccessDenied: Access Denied
May 06 16:01:07 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.8 Access Denied AccessDenied: Access Denied
May 06 16:01:07 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.98.42 Access Denied AccessDenied: Access Denied
May 06 16:01:08 1b8ea8a621f5 api[1211]: Failed to get device type build data for imx8mmebcrs08a2/2.85.2+rev4.prod Access Denied AccessDenied: Access Denied
May 06 16:01:08 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.102.1 Access Denied AccessDenied: Access Denied
May 06 16:01:08 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.98.45 Access Denied AccessDenied: Access Denied
May 06 16:01:08 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.25 Access Denied AccessDenied: Access Denied
May 06 16:01:08 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.7 Access Denied AccessDenied: Access Denied
May 06 16:01:08 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.98.41+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:08 1b8ea8a621f5 api[1211]: Failed to get device type build data for imx8mmebcrs08a2/2.85.2+rev4.dev Access Denied AccessDenied: Access Denied
May 06 16:01:08 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.11+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:09 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.98.42 Access Denied AccessDenied: Access Denied
May 06 16:01:09 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.24 Access Denied AccessDenied: Access Denied
May 06 16:01:09 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.6 Access Denied AccessDenied: Access Denied
May 06 16:01:09 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.53.9+rev1.prod Access Denied AccessDenied: Access Denied
May 06 16:01:09 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.11 Access Denied AccessDenied: Access Denied
May 06 16:01:09 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.98.41 Access Denied AccessDenied: Access Denied
May 06 16:01:10 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.4 Access Denied AccessDenied: Access Denied
May 06 16:01:10 1b8ea8a621f5 api[1211]: Failed to get device type build data for ccon-01/2.53.9+rev1.dev Access Denied AccessDenied: Access Denied
May 06 16:01:10 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.22 Access Denied AccessDenied: Access Denied
May 06 16:01:10 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.10 Access Denied AccessDenied: Access Denied
May 06 16:01:10 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.75.0+rev1.prod Access Denied AccessDenied: Access Denied
May 06 16:01:10 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.3 Access Denied AccessDenied: Access Denied
May 06 16:01:11 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.21 Access Denied AccessDenied: Access Denied
May 06 16:01:11 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.9 Access Denied AccessDenied: Access Denied
May 06 16:01:11 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.75.0+rev1.dev Access Denied AccessDenied: Access Denied
May 06 16:01:11 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.2 Access Denied AccessDenied: Access Denied
May 06 16:01:11 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.20 Access Denied AccessDenied: Access Denied
May 06 16:01:12 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.8 Access Denied AccessDenied: Access Denied
May 06 16:01:12 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.73.1+rev2.prod Access Denied AccessDenied: Access Denied
May 06 16:01:12 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.1+rev2 Access Denied AccessDenied: Access Denied
May 06 16:01:12 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.17 Access Denied AccessDenied: Access Denied
May 06 16:01:12 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.7+rev3 Access Denied AccessDenied: Access Denied
May 06 16:01:13 1b8ea8a621f5 api[1211]: Failed to get device type build data for nitrogen8mm-dwe/2.73.1+rev2.dev Access Denied AccessDenied: Access Denied
May 06 16:01:13 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.1+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:13 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.16 Access Denied AccessDenied: Access Denied
May 06 16:01:13 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.7+rev2 Access Denied AccessDenied: Access Denied
May 06 16:01:14 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.99.1 Access Denied AccessDenied: Access Denied
May 06 16:01:14 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.12+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:14 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.7+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:14 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.72.0+rev6 Access Denied AccessDenied: Access Denied
May 06 16:01:15 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.12 Access Denied AccessDenied: Access Denied
May 06 16:01:15 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.7 Access Denied AccessDenied: Access Denied
May 06 16:01:15 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.72.0+rev5 Access Denied AccessDenied: Access Denied
May 06 16:01:15 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.11 Access Denied AccessDenied: Access Denied
May 06 16:01:15 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.6+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:16 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.69.1+rev3.prod Access Denied AccessDenied: Access Denied
May 06 16:01:16 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.10 Access Denied AccessDenied: Access Denied
May 06 16:01:16 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.6 Access Denied AccessDenied: Access Denied
May 06 16:01:17 1b8ea8a621f5 api[1211]: Failed to get device type build data for pc-20/2.69.1+rev3.dev Access Denied AccessDenied: Access Denied
May 06 16:01:17 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.99.2 Access Denied AccessDenied: Access Denied
May 06 16:01:17 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.0+rev3 Access Denied AccessDenied: Access Denied
May 06 16:01:18 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.98.33+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:18 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.0+rev2 Access Denied AccessDenied: Access Denied
May 06 16:01:18 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.98.33 Access Denied AccessDenied: Access Denied
May 06 16:01:19 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.0+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:19 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.98.12+rev4 Access Denied AccessDenied: Access Denied
May 06 16:01:19 1b8ea8a621f5 api[1211]: Failed to get device type build data for lv-dart/2.101.0 Access Denied AccessDenied: Access Denied
May 06 16:01:20 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.98.12+rev2 Access Denied AccessDenied: Access Denied
May 06 16:01:21 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.98.12 Access Denied AccessDenied: Access Denied
May 06 16:01:22 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.95.8+rev2 Access Denied AccessDenied: Access Denied
May 06 16:01:22 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.95.8+rev1 Access Denied AccessDenied: Access Denied
May 06 16:01:23 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.94.4 Access Denied AccessDenied: Access Denied
May 06 16:01:24 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.88.4+rev4 Access Denied AccessDenied: Access Denied
May 06 16:01:25 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.88.4+rev2.prod Access Denied AccessDenied: Access Denied
May 06 16:01:26 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.88.4+rev2.dev Access Denied AccessDenied: Access Denied
May 06 16:01:26 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.88.4+rev1.prod Access Denied AccessDenied: Access Denied
May 06 16:01:27 1b8ea8a621f5 api[1211]: Failed to get device type build data for srd3-xavier/2.88.4+rev1.dev Access Denied AccessDenied: Access Denied

**Comment by shaunco** [comment]
Those errors are all related to https://github.com/balena-io/open-balena-api/issues/1433 , which is fixed in https://github.com/balena-io/open-balena-api/pull/1434 ... but requires that you specify the exact device types you want, see:
https://github.com/balena-io/open-balena-api/blob/9fd9697f37423c891aea9faa92e45a9ca0db2137/src/lib/config.ts#L87C48-L87C48

**Comment by DoJuSm** [comment]
I have a related question. 
in https://github.com/balena-io/open-balena-api/blob/9fd9697f37423c891aea9faa92e45a9ca0db2137/src/lib/config.ts#L87C48-L87C48 the comment mentions
```
/**
 * null: include all device type and device contract slugs
 * "x;y;z": include only the specified device type and contract slugs - note that you MUST list
 *          all dependent slugs as well so for hw.device-type/asus-tinker-board-s you would need:
 *          `arch.sw/armv7hf;hw.device-manufacturer/asus;hw.device-family/tinkerboard;hw.device-type/asus-tinker-board-s`
 * 		    For something like hw.device-type/iot-gate-imx8 you would need:
 * 			`arch.sw/aarch64;hw.device-type/iot-gate-imx8`
 *          (the order of the slugs in this variable does not matter)
 */
```
How does one figure out all dependent slugs given device type?
For example, we use:
 raspberrypi4-64
 raspberrypi3
 asus-tinker-board
 asus-tinker-board-s

What should CONTRACT_ALLOWLIST look like?

**Comment by shaunco** [comment]
@DoJuSm - I would suggest looking through https://github.com/balena-io/contracts/tree/master/contracts

For example, start with [hw.device-type/raspberrypi3/contract.json](https://github.com/balena-io/contracts/blob/master/contracts/hw.device-type/raspberrypi3/contract.json) and you'll see it references `"arch": "armv7hf"` on line 14, so for this you'd need:
- arch.sw/armv7hf
- hw.device-type/raspberrypi3

Doing the same for [hw.device-type/raspberrypi4-64/contract.json](https://github.com/balena-io/contracts/blob/master/contracts/hw.device-type/raspberrypi4-64/contract.json) gets you:
- arch.sw/aarch64
- hw.device-type/raspberrypi4-64

And for Doing the same for [hw.device-type/asus-tinker-board-s/contract.json](https://github.com/balena-io/contracts/blob/master/contracts/hw.device-type/asus-tinker-board-s/contract.json) gets you'll see both `"arch": "armv7hf"` and `"family": "family-tinkerboard"`, so you need:
- arch.sw/armv7hf
- hw.device-family/tinkerboard
- hw.device-type/asus-tinker-board-s

... but if you check [hw.device-family/tinkerboard/contract.json](https://github.com/balena-io/contracts/blob/master/contracts/hw.device-family/tinkerboard/contract.json) you'll see that it references `"manufacturedBy": "manufacturer-asus"` on line 8, so you also need:
- hw.device-manufacturer/asus

**Comment by thgreasi** [comment]
Hi,
I would like to let you know open-balena-api v31.1.0 should no longer log these warnings.
Can you give it a try and let us know?

Kind regards,
Thodoris
